apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: v5.49.0 # todo: update
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.13.2  # todo: update
    namespace: cert-manager
    includeCRDs: true
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.18.0  # todo: update
    namespace: istio-system
    includeCRDs: true
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.18.0  # todo: update
    namespace: istio-ingress
    includeCRDs: true
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.18.0  # todo: update
    namespace: istio-system
    includeCRDs: true
  - name: kiali-operator
    repo: https://kiali.org/helm-charts
    version: 1.70.0  # todo: update
    namespace: kiali-operator
    includeCRDs: true
  # todo: distributed-lgtm
  - name: strimzi-kafka-operator
    repo: https://strimzi.io/charts/
    version: 0.35.1  # todo: update
    namespace: kafka
    includeCRDs: true
  # todo: rabbitmq
  # todo: redis
  # todo: mongodb
  # todo: postgres
  # todo: mysql
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: v1.13.2  # todo: update
    namespace: rook-ceph
    includeCRDs: true
