apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: v7.6.8
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.16.0
    namespace: cert-manager
    includeCRDs: true
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.23.2
    namespace: istio-system
    includeCRDs: true
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.23.2
    namespace: istio-ingress
    includeCRDs: true
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.23.2
    namespace: istio-system
    includeCRDs: true
  - name: kiali-operator
    repo: https://kiali.org/helm-charts
    version: 1.89.7
    namespace: kiali-operator
    includeCRDs: true
  - name: lgtm-distributed
    repo: https://grafana.github.io/helm-charts
    version: 2.1.0
    namespace: lgtm-distributed
    includeCRDs: true
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: v1.15.3
    namespace: rook-ceph
    includeCRDs: true
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.16.6
    namespace: promtail
    includeCRDs: true
  - name: strimzi-kafka-operator
    repo: https://strimzi.io/charts/
    version: 0.43.0
    namespace: kafka
    includeCRDs: true
  - name: rabbitmq-cluster-operator
    repo: https://charts.bitnami.com/bitnami
    version: 4.3.24
    namespace: rabbitmq
    includeCRDs: true
