apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/caerulescens/helm-charts.git
    targetRevision: feature/updating-charts
    path: charts/app-of-apps
    helm:
      valuesObject:
        project:
          name: default
          description: application that launches other applications
          organization: caerulescens
          environment: dev
          region: local
          domain: caerulescens.test
          platform: minikube
          profile: default
          repository: https://github.com/caerulescens/kustomizations.git
          branch: feature/updating-charts
        network:
          enabled: true
          issuer: selfsigned
        logs:
          enabled: true
          level: info
          format: json
        metrics:
          enabled: true
        traces:
          enabled: true
        applications:
          istio:
            enabled: false
            base:
              namespace: istio-system
            istiod:
              namespace: istio-system
            gateway:
              namespace: istio-ingress
          certManager:
            enabled: true
            namespace: cert-manager
          kiali:
            enabled: true
            namespace: kiali-operator
          argocd:
            enabled: true
            namespace: argocd
          knative:
            enabled: false
            operator:
              namespace: default
            serving:
              namespace: knative-serving
            eventing:
              namespace: knative-eventing
          lgtm:
            enabled: false
            namespace: lgtm-distributed
          rook:
            enabled: false
            namespace: rook-ceph
          loki:
            enabled: false
            namespace: loki
          promtail:
            enabled: false
            namespace: promtail
          tempo:
            enabled: false
            namespace: tempo
          strimzi:
            enabled: false
            namespace: kafka
          rabbitmq:
            enabled: false
            namespace: rabbitmq
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
